#! Python3

hiddenimports= ['pygubu.builder',
				'pygubu.widgets',
				'pygubu.builder.builderobject',
				'pygubu.builder.tkstdwidgets',
				'pygubu.builder.ttkstdwidgets',
				'pygubu.builder.widgets.calendarframe',
				'pygubu.builder.widgets.combobox',
				'pygubu.builder.widgets.dialog',
				'pygubu.builder.widgets.editabletreeview',
				'pygubu.builder.widgets.pathchooserinput',
				'pygubu.builder.widgets.scrollbarhelper',
				'pygubu.builder.widgets.scrolledframe',
				'pygubu.builder.widgets.tkscrollbarhelper',
				'pygubu.builder.widgets.tkscrolledframe',
				'pygubu.widgets.accordionframe',
				'pygubu.widgets.autoarrangementframe',
				'pygubu.widgets.calendarframe',
				'pygubu.widgets.combobox',
				'pygubu.widgets.dialog',
				'pygubu.widgets.editabletreeview',
				'pygubu.widgets.pathchooserinput',
				'pygubu.widgets.scrollbarhelper',
				'pygubu.widgets.scrolledframe',
				'pygubu.widgets.simpletooltip',
				'pygubu.widgets.tkscrollbarhelper',
				'pygubu.widgets.tkscrolledframe',
				'pygubu.widgets.ttkspinbox']